version: '3.8'

services:
  weaviate:
    image: semitechnologies/weaviate:1.31.0
    ports:
      - "8080:8080"
    environment:
      - CLUSTER_HOSTNAME=node1
      - RAFT_BOOTSTRAP_EXPECT=1
      - RAFT_JOIN=
      - DISABLE_TELEMETRY=true
      - QUERY_DEFAULTS_LIMIT=25
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - ENABLE_MODULES=text2vec-openai
      - OPENAI_APIKEY=${OPENAI_API_KEY}
    volumes:
      - weaviate_data:/var/lib/weaviate

  ingest:
    depends_on:
      - weaviate
    build:
      context: .
      dockerfile: ingest/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - WEAVIATE_URL=http://weaviate:8080
    restart: always

  mcp:
    depends_on:
    - weaviate
    build:
      context: .
      dockerfile: mcp/Dockerfile
    ports:
      - "8010:8010"
    volumes:
      - .:/app
    environment:
      - WEAVIATE_URL=http://weaviate:8080
    restart: always

volumes:
  weaviate_data:
